### ISSUE TITLE
ERROR Caught exception executing shutdown hook null java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/async/DiscardingAsyncQueueFullPolicy

### ISSUE THREAD

**Issue by nimcoh0** [nimcoh0/Jdry#1]
on compiling SUT
2021-11-02 12:29:00,607 pool-2-thread-1 ERROR Caught exception executing shutdown hook null java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/async/DiscardingAsyncQueueFullPolicy
        at org.apache.logging.log4j.core.appender.AsyncAppender.stop(AsyncAppender.java:144)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:386)
        at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:389)
        at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:317)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:119)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:78)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.async.DiscardingAsyncQueueFullPolicy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more

**Comment by nimcoh0** [comment]
not produce
